[package]
name = "secp-verfication"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "1.5.6"
thiserror = "1.0.23"
libsecp256k1 = "0.7.0"